sudo: required
services:
  - docker

before_install:
  - docker build -t jonathankim/docker-react -f Dockerfile.dev .

script:
  - docker run jonathankim/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-504977403857"
  bucket_path: "docker-react"
  on:
    branch: master